### ISSUE TITLE
Add issue template to .github config

### ISSUE THREAD

**Issue by ijdoc** [edgeimpulse/ei-install-scripts#19]
We should add the below template as default to get used to writing nice & complete issues

--- Template starts here ---

## Expected Behavior
_Describe what should happen_

## Current Behavior
_Describe what happens instead of the expected behavior_

## Possible Causes/Solutions (optional)
_Suggest one or more fixes/reasons for the issue_

## Steps to Reproduce
_Provide a link to a test, example, or a set of steps to follow_

## Additional Context (optional)
_The device, browser, version, environment, etc. that this issue refers to_

**Comment by ijdoc** [comment]
@shrit I know you are capable of way more, but I'll leave you this one just to get your repo nicely setup

**Comment by shrit** [comment]
@ijdoc Thanks, nice warm-up. I open a PR in #20, let me know what do you think.

**Comment by ijdoc** [comment]
Ok so quick update. The template had a side effect of forcing the flow through an extra page in order to select the appropriate issue report, this causes unnecessary friction for such a low traffic repo. Moreover, that page also included the possibility to fill in a blank issue, which we do not want to expose and, as I can gather from github forums on the topic, a surprising amount of ppl end up using this option, which kind of defeats the purpose of templating.

Even when using the config.yml file inside the ISSUE_TEMPLATE folder and only having one template, github is not smart enough to figure out we only want one template to be automagically selected, so i went back to the old single-template method by using ISSUE_TEMPLATE.md directly (without the containing folder). 

The yaml front matter is not needed but doesn't hurt either, so I left it for posterity.

**Comment by shrit** [comment]
Yeah, agreed no need to have the folder, this PR does not have a high traffic and no need to report anything else other than issue.
